### ISSUE TITLE
Steps to prepare training data and start training?

### ISSUE THREAD

**Issue by dsbyprateekg** [quangdungluong/hf-ship-detection#1]
Thanks for sharing your winning code.
Can you please tell followings-
1. Which script have you used for training dataset preparation since you mentioned that you cut the original image into many patches with the size 400x400 and stride 300?
2. How to run the training code?

**Comment by quangdungluong** [comment]
Hi @dsbyprateekg,
1. The script I used to prepare training data is in `src/get_data.py`, you can modify `STRIDE` and `IMAGE_SIZE` to test different experiments. For convenience, I have published the training dataset at the following link: https://www.kaggle.com/datasets/lqdisme/ship-detection
2. Link to sample training notebook: https://www.kaggle.com/lqdisme/hf-ship-detection. You can also try the later versions of YOLO, I think the result might be better than the one I got. 

Never mind if you still have questions. Have a good day

**Comment by dsbyprateekg** [comment]
Thanks, it resolves my queries.
